# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
import math

REMNANT_FMT = "W{w:.2f} * H{h:.2f}"

class LuxtorLocation(models.Model):
    _name = "luxtor.location"
    _description = "Luxtor Location"
    _order = "name"

    name = fields.Char(default="Other")
    code = fields.Char()


class StockLocation(models.Model):
    _inherit = 'stock.location'

    # Flag used to identify the special remnant warehouse: WH/Treasure
    is_lx_treasure = fields.Boolean(
        string="Treasure Location",
        help=(
            "If checked, this location is used to store reusable remnant "
            "fabric generated by Luxtor manufacturing orders."
        ),
    )


class StockScrap(models.Model):
    _inherit = "stock.scrap"

    luxtor_waste_id = fields.Many2one(
        "luxtor.waste",
        string="Luxtor Waste",
        readonly=True,
        help="Origin Luxtor waste record for this scrap line.",
    )
    lx_width_m = fields.Float(string="Waste Width (m)", readonly=True)
    lx_height_m = fields.Float(string="Waste Height (m)", readonly=True)
    lx_area_m2 = fields.Float(string="Waste Area (m²)", readonly=True)


class LuxtorWaste(models.Model):
    """
    Each record represents ONE piece of fabric waste:
      - remnant: usable piece stored in WH/Treasure
      - roll_end: end of roll stored in WH/Treasure (then converted to remnant)
      - scrap: unusable piece moved to scrap location through stock.scrap

    Quantity is stored in LINEAR METERS (not m²).
    """
    _name = 'luxtor.waste'
    _description = 'Roller Fabric Waste / Remnants'
    _order = 'create_date desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    # ------------------------------------------------------------------
    # DEFAULTS
    # ------------------------------------------------------------------
    @api.model
    def _default_treasure_location(self):
        """Pick the first Treasure Location as default, if any."""
        loc = self.env['stock.location'].search(
            [('is_lx_treasure', '=', True)], limit=1
        )
        return loc.id if loc else False

    @api.model
    def _default_stock_location(self):
        loc = self.env.ref('stock.stock_location_stock', raise_if_not_found=False)
        return loc.id if loc else False

    # ------------------------------------------------------------------
    # FIELDS
    # ------------------------------------------------------------------
    name = fields.Char(
        compute='_compute_name',
        store=True,
    )

    production_id = fields.Many2one(
        'mrp.production',
        string="Manufacturing Order",
        ondelete='cascade',
        tracking=True,
    )

    product_id = fields.Many2one(
        'product.product',
        required=True,
        string="Fabric Product",
        tracking=True,
    )

    product_tmpl_id = fields.Many2one(
        'product.template',
        string="Fabric Template",
        related='product_id.product_tmpl_id',
        store=True,
        index=True,
    )

    lot_id = fields.Many2one(
        'stock.lot',
        string="Lot / Roll",
        tracking=True,
    )

    location_id = fields.Many2one(
        'stock.location',
        string="Location",
        required=True,
        help=(
            "For remnant type this is the destination internal location "
            "(Treasure by default). For scrap it is used as source location."
        ),
    )

    move_id = fields.Many2one(
        'stock.move',
        string="Creation Move",
        readonly=True,
        help="Stock move that created this waste piece (to Treasure or Scrap).",
    )

    consume_move_id = fields.Many2one(
        'stock.move',
        string="Consumption Move",
        readonly=True,
        help="Stock move that consumed this remnant for another MO.",
    )

    scrap_id = fields.Many2one(
        'stock.scrap',
        string="Scrap Order",
        readonly=True,
        help="Odoo scrap order created when this waste is scrapped.",
    )

    waste_type = fields.Selection(
        [
            ('remnant', 'Remnant'),
            ('roll_end', 'Roll End'),
            ('scrap', 'Scrap'),
        ],
        default='remnant',
        required=True,
        string="Type",
        tracking=True,
    )

    # Keep memory of original type (for list view)
    initial_waste_type = fields.Selection(
        [
            ('remnant', 'Remnant'),
            ('roll_end', 'Roll End'),
            ('scrap', 'Scrap'),
        ],
        string="Initial Type",
        readonly=True,
    )

    width_m = fields.Float(
        string="Width (m)",
        help="Remnant width in metres.",
        tracking=True,
    )
    height_m = fields.Float(
        string="Height (m)",
        help="Remnant height in metres (fabric direction).",
        tracking=True,
    )

    area_m2 = fields.Float(
        string="Area (m²)",
        compute='_compute_area',
        store=True,
    )

    qty = fields.Float(
        string="Qty (lm)",
        help="Linear metres stored for this waste piece.",
        tracking=True,
    )

    is_consumed = fields.Boolean(
        string="Consumed",
        default=False,
        readonly=True,
        help="Set to True when this remnant has been fully reused or scrapped.",
    )

    # ------------------------------------------------------------------
    # DEFAULT_GET / ONCHANGE
    # ------------------------------------------------------------------
    @api.model
    def default_get(self, fields_list):
        res = super().default_get(fields_list)
        ctx = self.env.context or {}
        active_model = ctx.get('active_model')
        active_id = ctx.get('active_id')

        # Default product from product/product.template if opened from stat button
        if 'product_id' in fields_list and not res.get('product_id') and active_id:
            if active_model == 'product.product':
                res['product_id'] = active_id
            elif active_model == 'product.template':
                tmpl = self.env['product.template'].browse(active_id)
                if tmpl and tmpl.product_variant_id:
                    res['product_id'] = tmpl.product_variant_id.id

        # Default location based on type
        if 'location_id' in fields_list and not res.get('location_id'):
            waste_type = res.get('waste_type') or 'remnant'
            if waste_type == 'remnant':
                res['location_id'] = self._default_treasure_location()
            else:
                res['location_id'] = self._default_stock_location()

        # Initial type at creation (will be updated by onchange if user changes type)
        if 'initial_waste_type' in fields_list and not res.get('initial_waste_type'):
            res['initial_waste_type'] = res.get('waste_type') or 'remnant'

        return res

    @api.onchange('waste_type')
    def _onchange_waste_type_location(self):
        """
        Simple rules:
          - remnant : destination internal (Treasure by default)
          - roll_end : source = WH/Stock
          - scrap    : source = WH/Stock

        Also keep initial_waste_type aligned with the chosen type,
        except when we already have roll_end as initial (we want to
        preserve that even after conversion to remnant).
        """
        stock_loc_id = self._default_stock_location()
        treasure_id = self._default_treasure_location()

        for rec in self:
            if rec.waste_type == 'remnant':
                if treasure_id:
                    rec.location_id = treasure_id
                elif rec.location_id and rec.location_id.usage != 'internal':
                    rec.location_id = False
            elif rec.waste_type in ('roll_end', 'scrap'):
                if stock_loc_id:
                    rec.location_id = stock_loc_id

            # Manage initial_waste_type
            if not rec.initial_waste_type:
                rec.initial_waste_type = rec.waste_type
            else:
                # If not originally roll_end, mirror the chosen type
                if rec.initial_waste_type != 'roll_end':
                    rec.initial_waste_type = rec.waste_type

    # ------------------------------------------------------------------
    # COMPUTES
    # ------------------------------------------------------------------
    @api.depends('width_m', 'height_m')
    def _compute_area(self):
        for r in self:
            w = max(r.width_m or 0.0, 0.0)
            h = max(r.height_m or 0.0, 0.0)
            r.area_m2 = w * h

    @api.depends(
        'production_id.lx_width_m',
        'production_id.lx_height_m',
        'width_m',
        'height_m',
        'product_id',
    )
    # def _compute_name(self):
    #     for r in self:
    #         W = float(r.production_id.lx_width_m or 0.0)
    #         H = float(r.production_id.lx_height_m or 0.0)

    #         if not (W and H) and (r.width_m and r.height_m):
    #             W = float(r.width_m)
    #             H = float(r.height_m)

    #         if W and H:
    #             r.name = REMNANT_FMT.format(w=W, h=H)
    #         else:
    #             r.name = r.product_id.display_name or _("Waste")


    @api.depends('width_m', 'height_m', 'product_id')
    def _compute_name(self):
        for r in self:
            W = float(r.width_m or 0.0)
            H = float(r.height_m or 0.0)

            if W and H:
                # Name based on the generated waste dimensions
                r.name = REMNANT_FMT.format(w=W, h=H)
            else:
                # Fallback: product name or generic label
                r.name = r.product_id.display_name or _("Waste")


    # ------------------------------------------------------------------
    # UTILITIES
    # ------------------------------------------------------------------
    def _compute_linear_qty(self, roll_width_m):
        self.ensure_one()
        roll_width_m = float(roll_width_m or 0.0)
        if roll_width_m <= 0:
            return 0.0
        area = max(self.width_m or 0.0, 0.0) * max(self.height_m or 0.0, 0.0)
        if area <= 0.0:
            return 0.0
        return area / roll_width_m

    def _get_roll_width_from_product(self, product):
        tmpl = product.product_tmpl_id
        roller_tags = getattr(tmpl, 'roller_width_ids', False)
        if roller_tags:
            vals = [float(getattr(t, 'value_cm', 0.0) or 0.0) for t in roller_tags]
            vals = [v for v in vals if v > 0]
            width_cm = max(vals) if vals else float(getattr(tmpl, 'width_cm', 0.0) or 0.0)
        else:
            width_cm = float(getattr(tmpl, 'width_cm', 0.0) or 0.0)
        return width_cm / 100.0 if width_cm else 0.0

    # ------------------------------------------------------------------
    # Manual processing button for remnant / roll_end / scrap
    # ------------------------------------------------------------------
    def action_process_waste(self):
        StockMove = self.env['stock.move'].sudo()
        StockMoveLine = self.env['stock.move.line'].sudo()
        StockScrap = self.env['stock.scrap'].sudo()
        Lot = self.env['stock.lot'].sudo()
        Location = self.env['stock.location'].sudo()
        Warehouse = self.env['stock.warehouse'].sudo()

        scrap_loc = self.env.ref(
            'stock.stock_location_scrapped',
            raise_if_not_found=False
        )
        stock_loc = self.env.ref(
            'stock.stock_location_stock',
            raise_if_not_found=False
        )

        # Fallbacks for scrap location
        if not scrap_loc:
            scrap_loc = Location.search(
                [('usage', '=', 'inventory'), ('name', 'ilike', 'scrap')],
                limit=1,
            )
        if not scrap_loc:
            wh = Warehouse.search([], limit=1)
            vals = {
                'name': 'Scrap',
                'usage': 'inventory',
            }
            if wh and wh.view_location_id:
                vals['location_id'] = wh.view_location_id.id
            scrap_loc = Location.create(vals)

        for waste in self:
            debug = []
            debug.append(
                "[WASTE DEBUG] Start action_process_waste for Waste %s (type=%s, initial=%s)"
                % (waste.name or 'N/A', waste.waste_type, waste.initial_waste_type or 'n/a')
            )

            if waste.move_id or waste.scrap_id:
                debug.append("[WASTE DEBUG] Waste already processed -> skip.")
                waste.message_post(body="  | ".join(debug))
                continue

            product = waste.product_id
            if not product:
                debug.append("[WASTE DEBUG] No product -> abort.")
                waste.message_post(body="  | ".join(debug))
                continue

            roll_width_m = waste._get_roll_width_from_product(product)
            debug.append(
                "[WASTE DEBUG] Roll width from product: %.4f m" % roll_width_m
            )
            if not roll_width_m:
                debug.append("[WASTE DEBUG] Roll width = 0 -> abort.")
                waste.message_post(body="  | ".join(debug))
                continue

            qty_lm = waste._compute_linear_qty(roll_width_m)
            debug.append(
                "[WASTE DEBUG] Computed linear qty from width=%.4f, height=%.4f -> qty_lm=%.4f"
                % (waste.width_m or 0.0, waste.height_m or 0.0, qty_lm)
            )

            # Scrap: only require non-zero dimensions
            if waste.waste_type == 'scrap':
                if (waste.width_m or 0.0) <= 0.0 or (waste.height_m or 0.0) <= 0.0:
                    debug.append("[WASTE DEBUG] Scrap with zero width/height -> abort.")
                    waste.message_post(body="  | ".join(debug))
                    continue
            else:
                if qty_lm <= 0:
                    debug.append("[WASTE DEBUG] qty_lm <= 0 -> abort.")
                    waste.message_post(body="  | ".join(debug))
                    continue

            # Lot / Roll
            lot = waste.lot_id
            if not lot:
                seq = waste.env['ir.sequence'].sudo().next_by_code('luxtor.waste.lot') or False
                lot_name = seq or ("LOT-%05d" % waste.id)
                lot = Lot.create({
                    "name": lot_name,
                    "product_id": product.id,
                })
                waste.lot_id = lot
                debug.append(
                    "[WASTE DEBUG] Created new lot: %s (id=%s)" % (lot.name, lot.id)
                )
            else:
                debug.append(
                    "[WASTE DEBUG] Using existing lot: %s (id=%s)" % (lot.name, lot.id)
                )

            # ----------------------------------------------------------
            # SCRAP: create move WH/Stock -> Scrap + stock.scrap(done)
            # ----------------------------------------------------------
            if waste.waste_type == 'scrap':
                # Force source WH/Stock when possible
                if stock_loc:
                    source_loc = stock_loc
                    debug.append(
                        "[WASTE DEBUG] Scrap source forced to WH/Stock: %s (id=%s)"
                        % (source_loc.display_name, source_loc.id)
                    )
                else:
                    source_loc = product.property_stock_production or \
                        product.property_stock_inventory
                    if source_loc:
                        debug.append(
                            "[WASTE DEBUG] Scrap source fallback: %s (id=%s)"
                            % (source_loc.display_name, source_loc.id)
                        )

                if not source_loc or not scrap_loc:
                    debug.append("[WASTE DEBUG] No source or scrap location -> abort.")
                    waste.message_post(body="  | ".join(debug))
                    continue

                debug.append(
                    "[WASTE DEBUG] Scrap destination: %s (id=%s)"
                    % (scrap_loc.display_name, scrap_loc.id)
                )

                # Create stock move (out of stock to scrap)
                move = StockMove.create({
                    "name": _("Waste %s (scrap)") % (waste.name or ''),
                    "product_id": product.id,
                    "product_uom": product.uom_id.id,
                    "product_uom_qty": qty_lm,
                    "location_id": source_loc.id,
                    "location_dest_id": scrap_loc.id,
                    "origin": waste.production_id.name or waste.name,
                })
                debug.append(
                    "[WASTE DEBUG] Created scrap move id=%s for qty_lm=%.4f"
                    % (move.id, qty_lm)
                )

                move._action_confirm()
                move._action_assign()

                if hasattr(move, "quantity_done"):
                    move.quantity_done = qty_lm
                    if move.move_line_ids:
                        move.move_line_ids.write({'lot_id': lot.id})
                else:
                    StockMoveLine.create({
                        "move_id": move.id,
                        "product_id": product.id,
                        "product_uom_id": product.uom_id.id,
                        "location_id": source_loc.id,
                        "location_dest_id": scrap_loc.id,
                        "qty_done": qty_lm,
                        "lot_id": lot.id,
                    })

                move._action_done()
                debug.append("[WASTE DEBUG] Scrap move %s done." % move.id)

                company = waste.production_id.company_id or product.company_id or self.env.company

                scrap_vals = {
                    "name": waste.name or False,                # <<< NEW: scrap gets same name as waste
                    "product_id": product.id,
                    "scrap_qty": qty_lm,
                    "product_uom_id": product.uom_id.id,
                    "location_id": source_loc.id,
                    "scrap_location_id": scrap_loc.id,
                    "origin": waste.production_id.name or waste.name,
                    "company_id": company.id,
                    "lot_id": lot.id,
                    "luxtor_waste_id": waste.id,
                    "lx_width_m": waste.width_m,
                    "lx_height_m": waste.height_m,
                    "lx_area_m2": waste.area_m2,
                }
                scrap = StockScrap.create(scrap_vals)
                debug.append(
                    "[WASTE DEBUG] Created stock.scrap id=%s (draft) for qty_lm=%.4f"
                    % (scrap.id, qty_lm)
                )

                # Mark scrap as done and link move
                try:
                    scrap.write({
                        "state": "done",
                        "date_done": fields.Datetime.now(),
                    })
                    if hasattr(scrap, "move_ids"):
                        scrap.write({"move_ids": [(4, move.id)]})
                    debug.append(
                        "[WASTE DEBUG] Scrap %s marked done and linked to move %s."
                        % (scrap.id, move.id)
                    )
                except Exception as e:
                    debug.append(
                        "[WASTE DEBUG] Warning: unable to link scrap to move: %s" % e
                    )

                waste.scrap_id = scrap.id
                waste.move_id = move.id
                waste.qty = qty_lm
                waste.is_consumed = True
                waste.location_id = scrap_loc

                if not waste.initial_waste_type or waste.initial_waste_type not in ('roll_end', 'scrap'):
                    waste.initial_waste_type = 'scrap'

                waste.message_post(body="  | ".join(debug))
                continue

            # ----------------------------------------------------------
            # REMNANT / ROLL END -> stock.move
            # ----------------------------------------------------------
            treasure = Location.search([('is_lx_treasure', '=', True)], limit=1)
            if not treasure:
                wh = Warehouse.search([], limit=1)
                vals = {
                    'name': 'Treasure',
                    'usage': 'internal',
                    'is_lx_treasure': True,
                }
                if wh and wh.view_location_id:
                    vals['location_id'] = wh.view_location_id.id
                treasure = Location.create(vals)
            debug.append(
                "[WASTE DEBUG] Using Treasure location: %s (id=%s)"
                % (treasure.display_name, treasure.id)
            )

            if waste.waste_type == 'remnant':
                if waste.production_id and waste.production_id.location_dest_id:
                    source_loc = waste.production_id.location_dest_id
                    debug.append(
                        "[WASTE DEBUG] Remnant source from MO dest: %s (id=%s)"
                        % (source_loc.display_name, source_loc.id)
                    )
                else:
                    source_loc = stock_loc or \
                        product.property_stock_production or \
                        product.property_stock_inventory
                    debug.append(
                        "[WASTE DEBUG] Remnant source fallback: %s (id=%s)"
                        % (source_loc.display_name, source_loc.id)
                    )
                dest_loc = waste.location_id or treasure
                if dest_loc.usage != 'internal':
                    dest_loc = treasure
                debug.append(
                    "[WASTE DEBUG] Remnant destination: %s (id=%s)"
                    % (dest_loc.display_name, dest_loc.id)
                )
            else:
                # roll_end
                source_loc = stock_loc or \
                    product.property_stock_production or \
                    product.property_stock_inventory
                dest_loc = treasure
                debug.append(
                    "[WASTE DEBUG] Roll end movement: %s -> %s"
                    % (
                        source_loc.display_name if source_loc else "n/a",
                        dest_loc.display_name,
                    )
                )

            if not source_loc or not dest_loc:
                debug.append("[WASTE DEBUG] Missing source or destination -> abort.")
                waste.message_post(body="  | ".join(debug))
                continue

            move = StockMove.create({
                "name": _("Waste %s (%s)") % (waste.name or '', waste.waste_type),
                "product_id": product.id,
                "product_uom": product.uom_id.id,
                "product_uom_qty": qty_lm,
                "location_id": source_loc.id,
                "location_dest_id": dest_loc.id,
                "origin": waste.production_id.name or waste.name,
            })
            debug.append(
                "[WASTE DEBUG] Created stock.move id=%s for qty_lm=%.4f"
                % (move.id, qty_lm)
            )

            move._action_confirm()
            move._action_assign()

            if hasattr(move, "quantity_done"):
                move.quantity_done = qty_lm
                if move.move_line_ids:
                    move.move_line_ids.write({'lot_id': lot.id})
            else:
                StockMoveLine.create({
                    "move_id": move.id,
                    "product_id": product.id,
                    "product_uom_id": product.uom_id.id,
                    "location_id": source_loc.id,
                    "location_dest_id": dest_loc.id,
                    "qty_done": qty_lm,
                    "lot_id": lot.id,
                })

            move._action_done()
            debug.append("[WASTE DEBUG] Move %s done." % move.id)

            waste.move_id = move.id
            waste.qty = qty_lm

            if not waste.initial_waste_type:
                waste.initial_waste_type = waste.waste_type

            if waste.waste_type == 'roll_end':
                waste.location_id = dest_loc
                debug.append(
                    "[WASTE DEBUG] Roll end kept as 'roll_end' but physically moved to Treasure."
                )

            waste.message_post(body="  | ".join(debug))
